import 'package:simple_tuner/features/tunings/tuning_preset.dart';

abstract final class TuningCatalog {
  static const standard = TuningPreset(
    name: 'Standard',
    category: TuningCategory.standard,
    notes: [
      TuningNote('E2', 40),
      TuningNote('A2', 45),
      TuningNote('D3', 50),
      TuningNote('G3', 55),
      TuningNote('B3', 59),
      TuningNote('E4', 64),
    ],
  );

  static const all = <TuningPreset>[
    standard,
    TuningPreset(
      name: 'Drop D',
      category: TuningCategory.power,
      notes: [
        TuningNote('D2', 38),
        TuningNote('A2', 45),
        TuningNote('D3', 50),
        TuningNote('G3', 55),
        TuningNote('B3', 59),
        TuningNote('E4', 64),
      ],
    ),
    TuningPreset(
      name: 'Double Drop D',
      category: TuningCategory.power,
      notes: [
        TuningNote('D2', 38),
        TuningNote('A2', 45),
        TuningNote('D3', 50),
        TuningNote('G3', 55),
        TuningNote('B3', 59),
        TuningNote('D4', 62),
      ],
    ),
    TuningPreset(
      name: 'D Modal',
      category: TuningCategory.power,
      notes: [
        TuningNote('D2', 38),
        TuningNote('A2', 45),
        TuningNote('D3', 50),
        TuningNote('G3', 55),
        TuningNote('A3', 57),
        TuningNote('D4', 62),
      ],
    ),
    TuningPreset(
      name: 'Drop C Sharp',
      category: TuningCategory.power,
      notes: [
        TuningNote('C#2', 37),
        TuningNote('G#2', 44),
        TuningNote('C#3', 49),
        TuningNote('F#3', 54),
        TuningNote('A#3', 58),
        TuningNote('D#4', 63),
      ],
    ),
    TuningPreset(
      name: 'Drop C',
      category: TuningCategory.power,
      notes: [
        TuningNote('C2', 36),
        TuningNote('G2', 43),
        TuningNote('C3', 48),
        TuningNote('F3', 53),
        TuningNote('A3', 57),
        TuningNote('D4', 62),
      ],
    ),
    TuningPreset(
      name: 'Drop B',
      category: TuningCategory.power,
      notes: [
        TuningNote('B1', 35),
        TuningNote('F#2', 42),
        TuningNote('B2', 47),
        TuningNote('E3', 52),
        TuningNote('G#3', 56),
        TuningNote('C#4', 61),
      ],
    ),
    TuningPreset(
      name: 'Drop A',
      category: TuningCategory.power,
      notes: [
        TuningNote('A1', 33),
        TuningNote('E2', 40),
        TuningNote('A2', 45),
        TuningNote('D3', 50),
        TuningNote('F#3', 54),
        TuningNote('B3', 59),
      ],
    ),
    TuningPreset(
      name: 'G Modal',
      category: TuningCategory.power,
      notes: [
        TuningNote('D2', 38),
        TuningNote('G2', 43),
        TuningNote('D3', 50),
        TuningNote('G3', 55),
        TuningNote('C4', 60),
        TuningNote('D4', 62),
      ],
    ),
    TuningPreset(
      name: 'Open C',
      category: TuningCategory.open,
      notes: [
        TuningNote('C2', 36),
        TuningNote('G2', 43),
        TuningNote('C3', 48),
        TuningNote('G3', 55),
        TuningNote('C4', 60),
        TuningNote('E4', 64),
      ],
    ),
    TuningPreset(
      name: 'Open E',
      category: TuningCategory.open,
      notes: [
        TuningNote('E2', 40),
        TuningNote('B2', 47),
        TuningNote('E3', 52),
        TuningNote('G#3', 56),
        TuningNote('B3', 59),
        TuningNote('E4', 64),
      ],
    ),
    TuningPreset(
      name: 'Open F',
      category: TuningCategory.open,
      notes: [
        TuningNote('C2', 36),
        TuningNote('F2', 41),
        TuningNote('C3', 48),
        TuningNote('F3', 53),
        TuningNote('A3', 57),
        TuningNote('F4', 65),
      ],
    ),
    TuningPreset(
      name: 'Open G',
      category: TuningCategory.open,
      notes: [
        TuningNote('D2', 38),
        TuningNote('G2', 43),
        TuningNote('D3', 50),
        TuningNote('G3', 55),
        TuningNote('B3', 59),
        TuningNote('D4', 62),
      ],
    ),
    TuningPreset(
      name: 'Open A',
      category: TuningCategory.open,
      notes: [
        TuningNote('E2', 40),
        TuningNote('A2', 45),
        TuningNote('C#3', 49),
        TuningNote('E3', 52),
        TuningNote('A3', 57),
        TuningNote('E4', 64),
      ],
    ),
    TuningPreset(
      name: 'Open A 2',
      category: TuningCategory.open,
      notes: [
        TuningNote('E2', 40),
        TuningNote('A2', 45),
        TuningNote('E3', 52),
        TuningNote('A3', 57),
        TuningNote('C#4', 61),
        TuningNote('E4', 64),
      ],
    ),
    TuningPreset(
      name: 'Open Am',
      category: TuningCategory.open,
      notes: [
        TuningNote('E2', 40),
        TuningNote('A2', 45),
        TuningNote('E3', 52),
        TuningNote('A3', 57),
        TuningNote('C4', 60),
        TuningNote('E4', 64),
      ],
    ),
    TuningPreset(
      name: 'Open Em',
      category: TuningCategory.open,
      notes: [
        TuningNote('E2', 40),
        TuningNote('B2', 47),
        TuningNote('E3', 52),
        TuningNote('G3', 55),
        TuningNote('B3', 59),
        TuningNote('E4', 64),
      ],
    ),
    TuningPreset(
      name: 'Open D',
      category: TuningCategory.open,
      notes: [
        TuningNote('D2', 38),
        TuningNote('A2', 45),
        TuningNote('D3', 50),
        TuningNote('F#3', 54),
        TuningNote('A3', 57),
        TuningNote('D4', 62),
      ],
    ),
    TuningPreset(
      name: 'Open Dm',
      category: TuningCategory.open,
      notes: [
        TuningNote('D2', 38),
        TuningNote('A2', 45),
        TuningNote('D3', 50),
        TuningNote('F3', 53),
        TuningNote('A3', 57),
        TuningNote('D4', 62),
      ],
    ),
    TuningPreset(
      name: 'Half Step Down',
      category: TuningCategory.extra,
      notes: [
        TuningNote('D#2', 39),
        TuningNote('G#2', 44),
        TuningNote('C#3', 49),
        TuningNote('F#3', 54),
        TuningNote('A#3', 58),
        TuningNote('D#4', 63),
      ],
    ),
    TuningPreset(
      name: 'Whole Step Down',
      category: TuningCategory.extra,
      notes: [
        TuningNote('D2', 38),
        TuningNote('G2', 43),
        TuningNote('C3', 48),
        TuningNote('F3', 53),
        TuningNote('A3', 57),
        TuningNote('D4', 62),
      ],
    ),
    TuningPreset(
      name: 'Plus 1',
      category: TuningCategory.extra,
      notes: [
        TuningNote('F2', 41),
        TuningNote('A#2', 46),
        TuningNote('D#3', 51),
        TuningNote('G#3', 56),
        TuningNote('C4', 60),
        TuningNote('F4', 65),
      ],
    ),
    TuningPreset(
      name: 'Plus 2',
      category: TuningCategory.extra,
      notes: [
        TuningNote('F#2', 42),
        TuningNote('B2', 47),
        TuningNote('E3', 52),
        TuningNote('A3', 57),
        TuningNote('C#4', 61),
        TuningNote('F#4', 66),
      ],
    ),
    TuningPreset(
      name: 'Double Daddy',
      category: TuningCategory.alternate,
      notes: [
        TuningNote('D2', 38),
        TuningNote('A2', 45),
        TuningNote('D3', 50),
        TuningNote('D3', 50),
        TuningNote('A3', 57),
        TuningNote('D4', 62),
      ],
    ),
    TuningPreset(
      name: 'All 4ths',
      category: TuningCategory.alternate,
      notes: [
        TuningNote('E2', 40),
        TuningNote('A2', 45),
        TuningNote('D3', 50),
        TuningNote('G3', 55),
        TuningNote('C4', 60),
        TuningNote('F4', 65),
      ],
    ),
    TuningPreset(
      name: 'NST',
      category: TuningCategory.alternate,
      notes: [
        TuningNote('C2', 36),
        TuningNote('G2', 43),
        TuningNote('D3', 50),
        TuningNote('A3', 57),
        TuningNote('E4', 64),
        TuningNote('G4', 67),
      ],
    ),
    TuningPreset(
      name: 'Ostrich',
      category: TuningCategory.alternate,
      notes: [
        TuningNote('D4', 62),
        TuningNote('D4', 62),
        TuningNote('D4', 62),
        TuningNote('D3', 50),
        TuningNote('D3', 50),
        TuningNote('D2', 38),
      ],
    ),
  ];
}
